### ISSUE TITLE
Agregar título Prólogo 

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#1]
Ya vi que está el Prólogo en la tabla de Contenido pero en la página del prólogo no sé visualiza la etiqueta
![IMG_20221017_114642](https://user-images.githubusercontent.com/115945527/196223276-72d468b1-9166-4eea-8d31-8cd586f5a813.jpg)

**Comment by Lagrang3** [comment]
La palabra <Prologo> la puse escondida porque me parecía innecesaria. También está oculta en la página de <Derechos de autor>.

**Comment by LuisGuerraC40** [comment]
Entiendo, déjala como lo hiciste pensé que era un título que aparecía en la página.
