### ISSUE TITLE
Propuesta de Título 

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#2]
Podrías poner como Título: Constitución de la República de Cuba (1940)

**Comment by Lagrang3** [comment]
Me parece bien.

**Comment by Lagrang3** [comment]
Ya hice los cambios en este commit: 5a8157d3922f5a195e600a7790386de004983179
Saldrá en la version 1.2

**Comment by LuisGuerraC40** [comment]
Ok
