### ISSUE TITLE
Más datos para metadatos 

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#3]
Autores: Miembros de la Convención Constituyente
Creación: Noviembre de 1939
Ratificación: 1 de julio de 1940
Promulgación: 10 de octubre de 1940

**Comment by Lagrang3** [comment]
Este argumento es ya más delicado. Según mi punto de vista: los metadatos son propiedades del archivo como recurso digital.
Sirve para el que tenga una colección de documentos digitales, para poderlos clasificar/ordenar según el autor (eg. Victor Hugo) o según la fecha de publicación. La C40 sería el único documento en toda tu biblioteca digital con una fecha de "Promulgación", una de "Ratificación" además de la fecha de "Creación".

Yo le pondría los siguientes metadatos:

Título: Constitución de la República de Cuba (1940)
Autor: Varios
Fecha de creación: Noviembre de 1939

Muchas veces los metadatos no reflejan los deseos de los usuarios. Pero no se puede complacer a todos.
Por ejemplo, yo tengo una vasta biblioteca de música en digital. Algunas de las canciones son obras clásicas compuestas por Mozart, Beethoven, etc, pero interpretadas por la orquesta sinfónica de Berlín, conducido por Karajan, con la participación del pianista Fulano y Mengano. En ese caso, ¿qué pones en el metadato "Artista"? Generalmente en los CDs ponen como artista al que interpreta, o sea el director de orquesta + nombre de la orquesta, etc, y no el compositor.

El problema es similar con algunos libros que me encuentro que son colecciones de intervenciones en conferencias, o reviews del estado del arte de una ciencia. En estos libros te encuentras que cada capítulo tiene un autor diferente y sin embargo en la portada ponen el nombre de la persona que hizo la recompilación.

Nosotros somos de hecho autores, no del texto, sino de este recurso digital. Esa información ya está por suerte plasmada en la sección de "Derechos de autor".

Alternativamente yo creo no estaría mal tampoco poner como "Autor" a la Asamblea Constituyente.
Pero tengo mis dudas.

**Comment by LuisGuerraC40** [comment]
Entiendo tu punto.

**Comment by Lagrang3** [comment]
Resuelto en este commit [6ce3060](https://github.com/Lagrang3/c40/commit/6ce3060a5a7646f0d00bddcbe979f9239cf2308d)
