### ISSUE TITLE
Propuesta de portada #1

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#4]
![IMG_20221018_090851](https://user-images.githubusercontent.com/115945527/196439331-972d9ff5-cf4b-4ff4-9267-af2e64a05a65.jpg)

**Comment by Lagrang3** [comment]
@LuisGuerraC40  ¿Sabes cuál es la historia detrás de esta imagen?

**Comment by LuisGuerraC40** [comment]
Pues no

**Comment by LuisGuerraC40** [comment]
> Es que parece la portada de la alguna edición física de la Constitución.

Es posible, después de hacer una búsqueda rápida en Google de "imágenes de la Constitución de 1940" y al parecer fue publicada por un club patriótico, solo que el internet está de bala y no he podido entrar al sitio

**Comment by Lagrang3** [comment]
No se nada de ese club patriótico. Esta hubiera sido una buena portada, pero con la duda acerca de ese club patriótico, mejor no arriesgarse.
