### ISSUE TITLE
Propuesta portada #2

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#5]
![IMG_20221018_134003](https://user-images.githubusercontent.com/115945527/196505167-fa37cdb9-562b-4ef3-a62f-e59c3b08b21e.jpg)

**Comment by Lagrang3** [comment]
La portada ya está. Añadida es este commit [9b44056](https://github.com/Lagrang3/c40/commit/9b440564f4251b6e0808ac50a62f955fb0026839).
