### ISSUE TITLE
Propuesta de portada #3

### ISSUE THREAD

**Issue by LuisGuerraC40** [Lagrang3/c40#6]
![IMG_20221018_133928](https://user-images.githubusercontent.com/115945527/196507258-793781c8-6657-45f3-bd2a-eef94870d6c4.jpg)

**Comment by Lagrang3** [comment]
Ese es el título justo: Constitución de la República de Cuba de 1940.

**Comment by Lagrang3** [comment]
Creo que todas las propuestas para la portada podías haberlas puesto en un mismo issue.

**Comment by Lagrang3** [comment]
La segunda es la que más me gusta. Solo habr'ia que ponerle el título por encima de la imagen.

**Comment by Lagrang3** [comment]
Ya añadí la portada.
